name: Reconstruct dpes

# Trigger workflow on push to the main branch
on:
  push:
    branches:
      - main

# Define the job
jobs:
  update_document:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up the programming environment (e.g., R, Python, Node.js)
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3'

      # Step 3: Install dependencies
      - name: Install R packages
        run: |
          Rscript -e "install.packages(c('dplyr', 'readxl', 'writexl', 'here'), repos='https://cloud.r-project.org/')"

      # Step 4: Run the code to update the document
      - name: Run update script
        run: |
          Rscript create_mock_data/reconstructing_dpes.R

      # Step 5: Commit and push the updated document
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add rmonize/DPE_KARMEN_P1_test.xlsx rmonize/DPE_KARMEN_P2_test.xlsx
          git commit -m "Update DPE_KARMEN_P1 and DPE_KARMEN_P2 files"
          git push
